### ISSUE TITLE
linux distribution

### ISSUE THREAD

**Issue by tutkudoruk** [bouncmpe/labs344#1]
Hello class,
I have two issues.I think I solved  one of them in pragmatic perspective but I will  send a question about it later.Regarding the other issue, in this link https://learn.microsoft.com/en-gb/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package  there are instructions about installing Linux distribution on the windows system.I want to know more about step-6 the most  convenient  Linux distribution for my computer.I do not know how I should make a precise analysis to decide for the most convenient one. I need opinions about how I should analyze my computer 
[MergeResult_2022_09_30_02_46_35.pdf](https://github.com/bouncmpe/labs344/files/9685523/MergeResult_2022_09_30_02_46_35.pdf)
properties to decide the best one.I am sharing the properties of my computer and system  above as MergeResult.
Best regards

**Comment by doganulus** [comment]
For software development, the latest LTS version of Ubuntu can be considered the default choice. Currently, it is Ubuntu 22.04. But Ubuntu 20.04 is also equally fine.

But the link you give above is for older versions of WSL. Have you simply tried to type `wsl --install`?

**Comment by tutkudoruk** [comment]
Hello,
Yes I have tried wsl -install and a menu appears but I can not be sure about the installed
[20221001_155113.pdf](https://github.com/bouncmpe/labs344/files/9690391/20221001_155113.pdf)
version of wsl .The menu that appears after writing wsl -install is like the above.However I could not understand well how I can see the installed version.I read the page https://learn.microsoft.com/en-gb/windows/wsl/install but it shows nothing about the version when I write wsl -l -v as the website of the link  says.It only writes windows subsystem for Linux has no installed distributions.I will be pleased if I get help.
Best regards

**Comment by gokceuludogan** [comment]
Could you try the suggested solutions [here](https://github.com/MicrosoftDocs/WSL/issues/1054#issue-782162629) and let us know if any of them works?
